apiVersion: v1
kind: Service
metadata:
  name: sentiment-model-stable
  labels:
    app: sentiment-model
spec:
  type: ClusterIP
  selector:
    app: sentiment-model
  ports:
    - port: 8000
      targetPort: 8000
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: sentiment-model-canary
  labels:
    app: sentiment-model
spec:
  type: ClusterIP
  selector:
    app: sentiment-model
  ports:
    - port: 8000
      targetPort: 8000
      name: http
